name: next_blog
description: A Flutter blog application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed: ^2.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  index_generator: ^3.0.0
  injectable_generator: ^1.5.3
  integration_test:
    sdk: flutter
  intl_generator: ^0.2.1
  intl_utils: ^2.6.1
  lint: ^1.8.2
  mocktail: 0.3.0

dependency_overrides:
  analyzer: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  arb_dir: translations
  output_dir: lib/src/common/presentation/localization/generated

index_generator:
  exclude:
    - '**.g.dart'
    - '**.freezed.dart'
    - '**/bloc/**_event.dart'
    - '**/bloc/**_state.dart'
    - '**/cubit/**_state.dart'
  indexes:
    - path: lib/src/base
      include:
        - '**'
      name: base
      library: base

    - path: lib/src/common
      include:
        - '**'
      exclude:
        - 'presentation/localization/generated/**'
      name: common
      library: common

    - path: lib/src/features
      include:
        - '**'
      name: features
      library: features
